# Describes the format for available zha services
execute:
  description: Execute custom zha service
  fields:
    command:
      description: Command name
      example: scan_device
      required: true
      selector:
        select:
          options:
            - add_group
            - add_to_group
            - all_routes_and_neighbours
            - attr_write
            - bind_group
            - bind_ieee
            - conf_report
            - ezsp_add_key
            - ezsp_clear_keys
            - ezsp_get_config_value
            - ezsp_get_ieee_by_nwk
            - ezsp_get_keys
            - ezsp_get_policy
            - ezsp_get_token
            - ezsp_get_value
            - ezsp_set_channel
            - ezsp_start_mfg
            - get_groups
            - get_routes_and_neighbours
            - get_zll_groups
            - handle_join
            - ieee_ping
            - leave
            - ota_notify
            - rejoin
            - remove_all_groups
            - remove_from_group
            - remove_group
            - scan_device
            - sinope
            - unbind_coordinator
            - unbind_group
            - zcl_cmd
            - zdo_flood_parent_annce
            - zdo_join_with_code
            - zdo_scan_now
            - zdo_update_nwk_id
            - zigpy_deconz
            - znp_backup
            - znp_nvram_backup
            - znp_nvram_reset
            - znp_nvram_restore
            - znp_restore
    ieee:
      description: "Entity name,\ndevice name, or\nIEEE address of the node to execute command"
      example: "00:0d:6f:00:05:7d:2d:34"
      selector:
        entity:
          integration: zha
    command_data:
      description: data for the command (in some cases more complex than text)
      example: attribute_scan
      selector:
        text:
