---
name: Release

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  release_zip_file:
    name: Prepare release asset
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      # - name: Get version
      #   id: version
      #   uses: home-assistant/actions/helpers/version@master

      - name: Set version number
        run: |
          python3 ${{ github.workspace }}/.github/scripts/update_hacs_manifest.py --version ${{ github.ref_name }}

      - name: Create zip
        run: |
          cd custom_components/zha_toolkit
          zip zha-toolkit.zip -r ./
      - name: Upload zip to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./custom_components/zha_toolkit/zha-toolkit.zip
          asset_name: zha-toolkit.zip
          tag: ${{ github.ref }}
          overwrite: true
