---
# https://github.com/marketplace/actions/toc-generator
on: push
name: TOC Generator
jobs:
  generateTOC:
    name: TOC Generator
    runs-on: ubuntu-latest
    steps:
      - uses: technote-space/toc-generator@v4
        with:
          FOLDING: true
          COMMIT_MESSAGE: TOC update
          COMMIT_NAME: '[bot] TOC'
          COMMIT_EMAIL: <[bot] TOC>
          CHECK_ONLY_DEFAULT_BRANCH: false
          CREATE_PR: false
